name: Build and Push Docker Image

on:
  push:
    branches: [ '*' ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry (optional)
        uses: docker/login-action@v3
        with:
          registry: your-registry-here 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: | 
            ${{ if (github.ref_name == 'main') }}selfbot-24:latest ${{ endif }} # Only on 'main' branch
            selfbot-24:${{ github.ref_name }} 
